#############################################################################
# Makefile for building: GrandPrix
# Generated by qmake (2.01a) (Qt 4.8.6) on: mer. avr. 8 18:12:40 2015
# Project:  GrandPrix.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -o Makefile GrandPrix.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -Ibin -Ibin
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = src/main.cpp \
		src/grandprix.cpp \
		src/gpcontrolview.cpp \
		src/gpmapview.cpp \
		src/gpmapselector.cpp \
		src/gpcontrol.cpp \
		src/gpmap.cpp \
		src/gpdriverselector.cpp \
		src/finishdialog.cpp \
		src/gpprogression.cpp \
		src/car.cpp \
		src/headless.cpp bin/moc_grandprix.cpp \
		bin/moc_gpcontrolview.cpp \
		bin/moc_gpmapview.cpp \
		bin/moc_gpmapselector.cpp \
		bin/moc_gpcontrol.cpp \
		bin/moc_gpmap.cpp \
		bin/moc_gpdriverselector.cpp \
		bin/moc_finishdialog.cpp \
		bin/moc_gpprogression.cpp \
		bin/moc_headless.cpp \
		bin/qrc_res.cpp
OBJECTS       = bin/main.o \
		bin/grandprix.o \
		bin/gpcontrolview.o \
		bin/gpmapview.o \
		bin/gpmapselector.o \
		bin/gpcontrol.o \
		bin/gpmap.o \
		bin/gpdriverselector.o \
		bin/finishdialog.o \
		bin/gpprogression.o \
		bin/car.o \
		bin/headless.o \
		bin/moc_grandprix.o \
		bin/moc_gpcontrolview.o \
		bin/moc_gpmapview.o \
		bin/moc_gpmapselector.o \
		bin/moc_gpcontrol.o \
		bin/moc_gpmap.o \
		bin/moc_gpdriverselector.o \
		bin/moc_finishdialog.o \
		bin/moc_gpprogression.o \
		bin/moc_headless.o \
		bin/qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		GrandPrix.pro
QMAKE_TARGET  = GrandPrix
DESTDIR       = 
TARGET        = GrandPrix

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): bin/ui_grandprix.h bin/ui_gpcontrolview.h bin/ui_gpmapview.h bin/ui_gpmapselector.h bin/ui_gpdriverselector.h bin/ui_finishdialog.h bin/ui_gpprogression.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GrandPrix.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile GrandPrix.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile GrandPrix.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/GrandPrix1.0.0 || $(MKDIR) bin/GrandPrix1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/GrandPrix1.0.0/ && $(COPY_FILE) --parents src/grandprix.h src/gpcontrolview.h src/gpmapview.h src/gpmapselector.h src/gpcontrol.h src/gpmap.h src/gpdriverselector.h src/finishdialog.h src/gpprogression.h src/car.h src/headless.h bin/GrandPrix1.0.0/ && $(COPY_FILE) --parents res.qrc bin/GrandPrix1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/grandprix.cpp src/gpcontrolview.cpp src/gpmapview.cpp src/gpmapselector.cpp src/gpcontrol.cpp src/gpmap.cpp src/gpdriverselector.cpp src/finishdialog.cpp src/gpprogression.cpp src/car.cpp src/headless.cpp bin/GrandPrix1.0.0/ && $(COPY_FILE) --parents src/grandprix.ui src/gpcontrolview.ui src/gpmapview.ui src/gpmapselector.ui src/gpdriverselector.ui src/finishdialog.ui src/gpprogression.ui bin/GrandPrix1.0.0/ && $(COPY_FILE) --parents GrandPrix_fr_FR.ts GrandPrix_en_EN.ts bin/GrandPrix1.0.0/ && (cd `dirname bin/GrandPrix1.0.0` && $(TAR) GrandPrix1.0.0.tar GrandPrix1.0.0 && $(COMPRESS) GrandPrix1.0.0.tar) && $(MOVE) `dirname bin/GrandPrix1.0.0`/GrandPrix1.0.0.tar.gz . && $(DEL_FILE) -r bin/GrandPrix1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: bin/moc_grandprix.cpp bin/moc_gpcontrolview.cpp bin/moc_gpmapview.cpp bin/moc_gpmapselector.cpp bin/moc_gpcontrol.cpp bin/moc_gpmap.cpp bin/moc_gpdriverselector.cpp bin/moc_finishdialog.cpp bin/moc_gpprogression.cpp bin/moc_headless.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) bin/moc_grandprix.cpp bin/moc_gpcontrolview.cpp bin/moc_gpmapview.cpp bin/moc_gpmapselector.cpp bin/moc_gpcontrol.cpp bin/moc_gpmap.cpp bin/moc_gpdriverselector.cpp bin/moc_finishdialog.cpp bin/moc_gpprogression.cpp bin/moc_headless.cpp
bin/moc_grandprix.cpp: src/gpcontrolview.h \
		src/gpcontrol.h \
		src/car.h \
		src/gpdriverselector.h \
		src/gpmapview.h \
		src/grandprix.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/grandprix.h -o bin/moc_grandprix.cpp

bin/moc_gpcontrolview.cpp: src/gpcontrol.h \
		src/car.h \
		src/gpdriverselector.h \
		src/gpcontrolview.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/gpcontrolview.h -o bin/moc_gpcontrolview.cpp

bin/moc_gpmapview.cpp: src/gpcontrol.h \
		src/car.h \
		src/gpmapview.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/gpmapview.h -o bin/moc_gpmapview.cpp

bin/moc_gpmapselector.cpp: src/gpmapselector.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/gpmapselector.h -o bin/moc_gpmapselector.cpp

bin/moc_gpcontrol.cpp: src/car.h \
		src/gpcontrol.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/gpcontrol.h -o bin/moc_gpcontrol.cpp

bin/moc_gpmap.cpp: src/gpmap.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/gpmap.h -o bin/moc_gpmap.cpp

bin/moc_gpdriverselector.cpp: src/gpdriverselector.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/gpdriverselector.h -o bin/moc_gpdriverselector.cpp

bin/moc_finishdialog.cpp: src/finishdialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/finishdialog.h -o bin/moc_finishdialog.cpp

bin/moc_gpprogression.cpp: src/gpprogression.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/gpprogression.h -o bin/moc_gpprogression.cpp

bin/moc_headless.cpp: src/gpcontrol.h \
		src/car.h \
		src/headless.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/headless.h -o bin/moc_headless.cpp

compiler_rcc_make_all: bin/qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) bin/qrc_res.cpp
bin/qrc_res.cpp: res.qrc \
		GrandPrix_fr_FR.qm \
		res/out.png \
		res/goal.png \
		res/current.png \
		res/oil.png \
		res/normal.png \
		res/available1.png \
		res/car1.png \
		res/available2.png \
		res/car2.png \
		res/available3.png \
		res/car3.png \
		res/sand.png
	/usr/lib/i386-linux-gnu/qt4/bin/rcc -name res res.qrc -o bin/qrc_res.cpp

compiler_image_collection_make_all: bin/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) bin/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: bin/ui_grandprix.h bin/ui_gpcontrolview.h bin/ui_gpmapview.h bin/ui_gpmapselector.h bin/ui_gpdriverselector.h bin/ui_finishdialog.h bin/ui_gpprogression.h
compiler_uic_clean:
	-$(DEL_FILE) bin/ui_grandprix.h bin/ui_gpcontrolview.h bin/ui_gpmapview.h bin/ui_gpmapselector.h bin/ui_gpdriverselector.h bin/ui_finishdialog.h bin/ui_gpprogression.h
bin/ui_grandprix.h: src/grandprix.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic src/grandprix.ui -o bin/ui_grandprix.h

bin/ui_gpcontrolview.h: src/gpcontrolview.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic src/gpcontrolview.ui -o bin/ui_gpcontrolview.h

bin/ui_gpmapview.h: src/gpmapview.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic src/gpmapview.ui -o bin/ui_gpmapview.h

bin/ui_gpmapselector.h: src/gpmapselector.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic src/gpmapselector.ui -o bin/ui_gpmapselector.h

bin/ui_gpdriverselector.h: src/gpdriverselector.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic src/gpdriverselector.ui -o bin/ui_gpdriverselector.h

bin/ui_finishdialog.h: src/finishdialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic src/finishdialog.ui -o bin/ui_finishdialog.h

bin/ui_gpprogression.h: src/gpprogression.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic src/gpprogression.ui -o bin/ui_gpprogression.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

bin/main.o: src/main.cpp src/grandprix.h \
		src/gpcontrolview.h \
		src/gpcontrol.h \
		src/car.h \
		src/gpdriverselector.h \
		src/gpmapview.h \
		src/headless.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/main.o src/main.cpp

bin/grandprix.o: src/grandprix.cpp src/grandprix.h \
		src/gpcontrolview.h \
		src/gpcontrol.h \
		src/car.h \
		src/gpdriverselector.h \
		src/gpmapview.h \
		bin/ui_grandprix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/grandprix.o src/grandprix.cpp

bin/gpcontrolview.o: src/gpcontrolview.cpp src/finishdialog.h \
		src/gpcontrol.h \
		src/car.h \
		src/gpcontrolview.h \
		src/gpdriverselector.h \
		bin/ui_gpcontrolview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gpcontrolview.o src/gpcontrolview.cpp

bin/gpmapview.o: src/gpmapview.cpp src/gpmapview.h \
		src/gpcontrol.h \
		src/car.h \
		bin/ui_gpmapview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gpmapview.o src/gpmapview.cpp

bin/gpmapselector.o: src/gpmapselector.cpp src/gpmapselector.h \
		bin/ui_gpmapselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gpmapselector.o src/gpmapselector.cpp

bin/gpcontrol.o: src/gpcontrol.cpp src/gpcontrol.h \
		src/car.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gpcontrol.o src/gpcontrol.cpp

bin/gpmap.o: src/gpmap.cpp src/gpmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gpmap.o src/gpmap.cpp

bin/gpdriverselector.o: src/gpdriverselector.cpp src/gpdriverselector.h \
		bin/ui_gpdriverselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gpdriverselector.o src/gpdriverselector.cpp

bin/finishdialog.o: src/finishdialog.cpp src/finishdialog.h \
		bin/ui_finishdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/finishdialog.o src/finishdialog.cpp

bin/gpprogression.o: src/gpprogression.cpp src/gpprogression.h \
		bin/ui_gpprogression.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/gpprogression.o src/gpprogression.cpp

bin/car.o: src/car.cpp src/car.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/car.o src/car.cpp

bin/headless.o: src/headless.cpp src/headless.h \
		src/gpcontrol.h \
		src/car.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/headless.o src/headless.cpp

bin/moc_grandprix.o: bin/moc_grandprix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_grandprix.o bin/moc_grandprix.cpp

bin/moc_gpcontrolview.o: bin/moc_gpcontrolview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gpcontrolview.o bin/moc_gpcontrolview.cpp

bin/moc_gpmapview.o: bin/moc_gpmapview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gpmapview.o bin/moc_gpmapview.cpp

bin/moc_gpmapselector.o: bin/moc_gpmapselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gpmapselector.o bin/moc_gpmapselector.cpp

bin/moc_gpcontrol.o: bin/moc_gpcontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gpcontrol.o bin/moc_gpcontrol.cpp

bin/moc_gpmap.o: bin/moc_gpmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gpmap.o bin/moc_gpmap.cpp

bin/moc_gpdriverselector.o: bin/moc_gpdriverselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gpdriverselector.o bin/moc_gpdriverselector.cpp

bin/moc_finishdialog.o: bin/moc_finishdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_finishdialog.o bin/moc_finishdialog.cpp

bin/moc_gpprogression.o: bin/moc_gpprogression.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_gpprogression.o bin/moc_gpprogression.cpp

bin/moc_headless.o: bin/moc_headless.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_headless.o bin/moc_headless.cpp

bin/qrc_res.o: bin/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/qrc_res.o bin/qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

